name: ZMK Firmware Build

on:
  push:
    paths:
      - 'zmk_firmware/**'

jobs:
  zmk_firmware:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: "zmk_firmware"
